import React from 'react';
import { ComplianceReport, InventorySKU, StoredFile } from '../types';
import { Button } from './Button';

interface TechSheetProps {
  image: string | null;
  report: ComplianceReport | null;
  sku: InventorySKU | null;
  projectName: string;
  templateDimensions?: string;
}

export const TechSheet: React.FC<TechSheetProps> = ({ 
  image, 
  report, 
  sku, 
  projectName,
  templateDimensions 
}) => {

  const handlePrint = () => {
    window.print();
  };

  if (!image || !report) {
    return (
      <div className="flex flex-col items-center justify-center h-96 bg-gray-800/30 rounded-2xl border border-dashed border-gray-700">
        <p className="text-gray-500 mb-4">Generate an image and run a compliance scan to create a Data Sheet.</p>
      </div>
    );
  }

  return (
    <div className="max-w-4xl mx-auto">
      <div className="mb-4 flex justify-end print:hidden">
        <Button onClick={handlePrint} variant="primary" className="flex items-center gap-2">
          <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m2 4h6a2 2 0 002-2v-4a2 2 0 00-2-2H9a2 2 0 00-2 2v4a2 2 0 002 2zm8-12V5a2 2 0 00-2-2H9a2 2 0 00-2 2v4h10z" />
          </svg>
          Print / Save PDF
        </Button>
      </div>

      {/* Printable Area */}
      <div className="bg-white text-gray-900 p-8 rounded-sm shadow-xl print:shadow-none print:w-full print:absolute print:top-0 print:left-0 print:m-0">
        
        {/* Header */}
        <div className="border-b-2 border-gray-900 pb-4 mb-8 flex justify-between items-end">
          <div>
            <h1 className="text-3xl font-bold uppercase tracking-tight text-gray-900">Technical Data Sheet</h1>
            <p className="text-gray-500 text-sm mt-1">Generated by NanoPack Studio</p>
          </div>
          <div className="text-right">
            <p className="font-mono text-lg font-bold">{sku?.sku || 'DRAFT-SKU'}</p>
            <p className="text-sm text-gray-500">{new Date().toLocaleDateString()}</p>
          </div>
        </div>

        <div className="grid grid-cols-3 gap-8 mb-8">
          {/* Main Image */}
          <div className="col-span-1">
            <div className="aspect-[3/4] border border-gray-200 bg-gray-50 rounded flex items-center justify-center p-4">
              <img src={image} alt="Product Spec" className="max-w-full max-h-full object-contain" />
            </div>
            <div className="mt-2 text-center text-xs text-gray-400">
              Visual Reference v1.0
            </div>
          </div>

          {/* Specs Table */}
          <div className="col-span-2 space-y-6">
            <div>
              <h2 className="text-sm font-bold uppercase border-b border-gray-300 pb-1 mb-3 text-gray-500">Product Specifications</h2>
              <table className="w-full text-sm">
                <tbody>
                  <tr className="border-b border-gray-100">
                    <td className="py-2 font-medium text-gray-500 w-1/3">Project Name</td>
                    <td className="py-2 font-bold">{projectName}</td>
                  </tr>
                  <tr className="border-b border-gray-100">
                    <td className="py-2 font-medium text-gray-500">Category</td>
                    <td className="py-2">{sku?.category || report.detectedIndustry}</td>
                  </tr>
                  <tr className="border-b border-gray-100">
                    <td className="py-2 font-medium text-gray-500">Dimensions</td>
                    <td className="py-2">{templateDimensions || sku?.dimensions || 'N/A'}</td>
                  </tr>
                  <tr className="border-b border-gray-100">
                    <td className="py-2 font-medium text-gray-500">Barcode Type</td>
                    <td className="py-2">{report.barcodeAnalysis.type || 'Missing'}</td>
                  </tr>
                </tbody>
              </table>
            </div>

            {/* Marketing Copy (Extracted) */}
            {report.marketingCopy && (
               <div>
                <h2 className="text-sm font-bold uppercase border-b border-gray-300 pb-1 mb-3 text-gray-500">Marketing Claims</h2>
                <div className="bg-gray-50 p-4 rounded border border-gray-100">
                  <p className="font-bold text-lg mb-2">{report.marketingCopy.headline}</p>
                  <p className="text-sm text-gray-600 mb-2 italic">{report.marketingCopy.flavorProfile}</p>
                  <ul className="list-disc list-inside text-sm space-y-1">
                    {report.marketingCopy.claims.map((claim, i) => (
                      <li key={i}>{claim}</li>
                    ))}
                  </ul>
                </div>
              </div>
            )}
          </div>
        </div>

        {/* Compliance Section */}
        <div className="mb-8">
           <h2 className="text-sm font-bold uppercase border-b border-gray-300 pb-1 mb-3 text-gray-500">Regulatory Compliance ({report.regulatoryBody})</h2>
           
           <div className="grid grid-cols-2 gap-4">
              <div className={`p-4 rounded border ${report.score > 85 ? 'bg-green-50 border-green-200' : 'bg-red-50 border-red-200'}`}>
                 <div className="flex items-center justify-between mb-2">
                   <span className="font-bold text-sm uppercase">Safety Score</span>
                   <span className="text-2xl font-bold">{report.score}/100</span>
                 </div>
                 <p className="text-xs">{report.status.toUpperCase()}</p>
              </div>

              <div className="p-4 rounded border border-gray-200 bg-gray-50">
                <p className="font-bold text-sm uppercase mb-2">Detected Ingredients</p>
                <p className="text-xs font-mono text-gray-600 leading-relaxed">
                  {report.ingredientAnalysis.found ? report.ingredientAnalysis.text : 'No ingredients detected.'}
                </p>
                {report.ingredientAnalysis.flaggedIngredients.length > 0 && (
                   <div className="mt-2 pt-2 border-t border-gray-200">
                     <p className="text-xs font-bold text-red-600">Allergen/Prohibited Flags:</p>
                     <p className="text-xs text-red-500">{report.ingredientAnalysis.flaggedIngredients.join(', ')}</p>
                   </div>
                )}
              </div>
           </div>
        </div>

        {/* Signature Block */}
        <div className="grid grid-cols-2 gap-16 mt-12 pt-8 border-t-2 border-gray-900">
          <div>
            <div className="border-b border-gray-400 h-8"></div>
            <p className="text-xs text-gray-500 mt-1">Approved By (QA)</p>
          </div>
          <div>
            <div className="border-b border-gray-400 h-8"></div>
            <p className="text-xs text-gray-500 mt-1">Date</p>
          </div>
        </div>

      </div>
    </div>
  );
};